// Mechanical registration/downsampling of imagegen sprites; no substitute art.
import Foundation
import CoreGraphics
import ImageIO
import UniformTypeIdentifiers
let root=URL(fileURLWithPath:CommandLine.arguments[1])
let folder=root.appendingPathComponent("art/abstract")
try FileManager.default.createDirectory(at:folder,withIntermediateDirectories:true)
func ctx(_ w:Int,_ h:Int)->CGContext{CGContext(data:nil,width:w,height:h,bitsPerComponent:8,bytesPerRow:w*4,space:CGColorSpace(name:CGColorSpace.sRGB)!,bitmapInfo:CGImageAlphaInfo.premultipliedLast.rawValue)!}
var inputs:[CGImage]=[]
var left=Int.max,top=Int.max,right=0,bottom=0
for (i,name) in ["clever-head","clever-jaw"].enumerated(){
 let original=folder.appendingPathComponent(name+"-source-v1.png")
 if !FileManager.default.fileExists(atPath:original.path){try FileManager.default.copyItem(at:URL(fileURLWithPath:CommandLine.arguments[i+2]),to:original)}
 let image=CGImageSourceCreateImageAtIndex(CGImageSourceCreateWithURL(original as CFURL,nil)!,0,nil)!
 if let first=inputs.first{precondition(first.width==image.width && first.height==image.height,"Variants must share canvas registration")}
 inputs.append(image)
 let raw=ctx(image.width,image.height);raw.draw(image,in:CGRect(x:0,y:0,width:image.width,height:image.height))
 let b=raw.data!.assumingMemoryBound(to:UInt8.self);var clear=0
 for y in 0..<image.height{for x in 0..<image.width{let a=b[(y*image.width+x)*4+3];if a<8{clear+=1};if a>32{left=min(left,x);right=max(right,x);top=min(top,y);bottom=max(bottom,y)}}}
 precondition(clear>image.width*image.height/10,"Generated transparent alpha required")
}
// Shared crop, not independent alpha trimming: the upper skull never jumps.
let crop=CGRect(x:left,y:top,width:right-left+1,height:bottom-top+1)
let w=55,scale=53.0/Double(right-left+1),h=Int(ceil(Double(bottom-top+1)*scale))+2
var arrays:[String]=[]
for (i,name) in ["clever-head","clever-jaw"].enumerated(){
 let c=ctx(w,h);c.interpolationQuality = .high
 c.draw(inputs[i].cropping(to:crop)!,in:CGRect(x:1,y:1,width:53,height:Double(bottom-top+1)*scale))
 let encoder=CGImageDestinationCreateWithURL(folder.appendingPathComponent(name+"-native-v1.png") as CFURL,UTType.png.identifier as CFString,1,nil)!
 CGImageDestinationAddImage(encoder,c.makeImage()!,nil);precondition(CGImageDestinationFinalize(encoder))
 let b=c.data!.assumingMemoryBound(to:UInt8.self);var rows:[String]=[]
 for y in 0..<h{var row:[String]=[];for x in 0..<w{let p=(y*w+x)*4,a=UInt32(b[p+3]);let r=a>0 ? min(255,UInt32(b[p])*255/a):0,g=a>0 ? min(255,UInt32(b[p+1])*255/a):0,blue=a>0 ? min(255,UInt32(b[p+2])*255/a):0;row.append(String(format:"0x%08x",a<<24|r<<16|g<<8|blue))};rows.append(row.joined(separator:","))}
 arrays.append("inline constexpr uint32_t \(i==0 ? "Neutral":"Jaw")[]={\n"+rows.joined(separator:",\n")+"\n};")
}
let header="// Generated by scripts/register-clever-head.swift from imagegen head variants.\n#pragma once\n#include <cstdint>\nnamespace CleverHeadPixels { inline constexpr int Width=\(w),Height=\(h);\n"+arrays.joined(separator:"\n")+"\n}\n"
try header.write(to:root.appendingPathComponent("src/CleverHeadPixels.h"),atomically:true,encoding:.utf8)
print("Shared source crop \(crop), native \(w)x\(h), scale \(scale)")
