// Register generated prop to the existing newspaper rig. Crop/scale only.
import Foundation
import CoreGraphics
import ImageIO
import UniformTypeIdentifiers
let root=URL(fileURLWithPath:CommandLine.arguments[1])
let input=URL(fileURLWithPath:CommandLine.arguments[2])
let folder=root.appendingPathComponent("art/abstract")
try FileManager.default.createDirectory(at:folder,withIntermediateDirectories:true)
let original=folder.appendingPathComponent("phone-source-v1.png")
if !FileManager.default.fileExists(atPath:original.path){try FileManager.default.copyItem(at:input,to:original)}
let image=CGImageSourceCreateImageAtIndex(CGImageSourceCreateWithURL(original as CFURL,nil)!,0,nil)!
func ctx(_ w:Int,_ h:Int)->CGContext{CGContext(data:nil,width:w,height:h,bitsPerComponent:8,bytesPerRow:w*4,space:CGColorSpace(name:CGColorSpace.sRGB)!,bitmapInfo:CGImageAlphaInfo.premultipliedLast.rawValue)!}
let raw=ctx(image.width,image.height);raw.draw(image,in:CGRect(x:0,y:0,width:image.width,height:image.height))
let bytes=raw.data!.assumingMemoryBound(to:UInt8.self)
var x0=image.width,y0=image.height,x1=0,y1=0,clear=0
for y in 0..<image.height{for x in 0..<image.width{let a=bytes[(y*image.width+x)*4+3];if a<8{clear+=1};if a>32{x0=min(x0,x);x1=max(x1,x);y0=min(y0,y);y1=max(y1,y)}}}
precondition(clear>image.width*image.height/10 && x1>x0,"Real transparent sprite required")
let crop=image.cropping(to:CGRect(x:x0,y:y0,width:x1-x0+1,height:y1-y0+1))!
let w=86,h=82,c=ctx(w,h);c.interpolationQuality = .high
// Native hands grip the newspaper around these coordinates, in its own space.
c.draw(crop,in:CGRect(x:9,y:18,width:74,height:43))
let final=c.makeImage()!,destination=folder.appendingPathComponent("phone-native-v1.png")
let encoder=CGImageDestinationCreateWithURL(destination as CFURL,UTType.png.identifier as CFString,1,nil)!
CGImageDestinationAddImage(encoder,final,nil);precondition(CGImageDestinationFinalize(encoder))
let b=c.data!.assumingMemoryBound(to:UInt8.self)
var rows:[String]=[]
for y in 0..<h{var row:[String]=[];for x in 0..<w{let i=(y*w+x)*4,a=UInt32(b[i+3]);let r=a>0 ? min(255,UInt32(b[i])*255/a):0,g=a>0 ? min(255,UInt32(b[i+1])*255/a):0,blue=a>0 ? min(255,UInt32(b[i+2])*255/a):0;row.append(String(format:"0x%08x",a<<24|r<<16|g<<8|blue))};rows.append(row.joined(separator:","))}
let header="// Generated by scripts/register-abstract-phone.swift from art/abstract/phone-source-v1.png.\n#pragma once\n#include <cstdint>\nnamespace AbstractPhonePixels { inline constexpr int Width=86,Height=82;\ninline constexpr uint32_t Pixels[]={\n"+rows.joined(separator:",\n")+"\n}; }\n"
try header.write(to:root.appendingPathComponent("src/AbstractPhonePixels.h"),atomically:true,encoding:.utf8)
print("Registered one phone sprite at native 86x82 rig dimensions; original body/arms unchanged.")
