// Rebuild only the missing complete glyphs, not the game's existing font.
// CoreText outlines supply the actual Unicode characters; no radical collage.
import Foundation
import CoreText
import CoreGraphics
let output = CommandLine.arguments[1]
let size = 64
let font = CTFontCreateWithName("STKaiti" as CFString, 58, nil)
var result = "// Generated by scripts/render-exact-glyphs.swift using CoreText STKaiti.\n#pragma once\nnamespace ExactGlyphPixels {\ninline constexpr int Size=64;\n"
let glyphs = [("Wrap", "裹"), ("Stack", "叠"), ("Green", "绿")] + "缘九脾省瞄脸班概武巴颚凑翻偷判耗血殴扇药扩招煲档掀盖滚贷蹲尊写刹奔撤戚租届流".map { character in
    let text = String(character)
    return ("U" + String(text.unicodeScalars.first!.value, radix:16).uppercased(), text)
}
for (name, text) in glyphs {
    var code = Array(text.utf16)[0], glyph: CGGlyph = 0
    guard CTFontGetGlyphsForCharacters(font, &code, &glyph, 1), glyph != 0,
          let path = CTFontCreatePathForGlyph(font, glyph, nil) else { fatalError("Missing glyph \(text)") }
    let bounds = path.boundingBoxOfPath
    let ctx = CGContext(data:nil,width:size,height:size,bitsPerComponent:8,bytesPerRow:size,
                        space:CGColorSpaceCreateDeviceGray(),bitmapInfo:CGImageAlphaInfo.none.rawValue)!
    ctx.setFillColor(gray:1,alpha:1)
    ctx.translateBy(x:2-bounds.minX*(60/bounds.width),y:2-bounds.minY*(60/bounds.height))
    ctx.scaleBy(x:60/bounds.width,y:60/bounds.height)
    ctx.setStrokeColor(gray:1,alpha:1);ctx.setLineWidth(1.2)
    ctx.addPath(path);ctx.drawPath(using:.fillStroke)
    let pixels=ctx.data!.assumingMemoryBound(to:UInt8.self)
    let hex=Array("0123456789abcdef")
    result += "inline constexpr char \(name)[]=\n"
    // CGContext rows run top to bottom for the generated bitmap.
    for y in 0..<size {
        result += "\"" + String((0..<size).map { hex[Int(pixels[y*size+$0])*15/255] }) + "\"\n"
    }
    result += ";\n"
}
result += "struct Glyph {char32_t character;const char* key;const char* pixels;};\ninline constexpr Glyph Glyphs[]={\n"
for (name, text) in glyphs { result += "{U'\(text)',\"\(name.uppercased())\",\(name)},\n" }
result += "};\n}\n"
try result.write(toFile:output,atomically:true,encoding:.utf8)
print("Generated \(glyphs.count) complete glyphs using \(CTFontCopyPostScriptName(font))")
